#! /usr/bin/env python

import time
import curses

CONTENT = "      "

def init_gradient():
    gradient = [48, 47, 82, 118, 154, 190, 220, 208, 202, 196, 160, 124, 88, 88, 52, 52]

    for i, c in enumerate(gradient):
        curses.init_pair(i + 1, 0, c)

def set_background(stdscr):
    curses.init_pair(17, 0, 236)
    stdscr.bkgdset(" ", curses.color_pair(17))

def draw_block(stdscr, x, y, speed):
    for l in range(0, 3):
        stdscr.addstr(y + l,
                      x + (speed * len(CONTENT)),
                      CONTENT,
                      curses.color_pair(speed + 1))

def main(stdscr):
    init_gradient()
    set_background(stdscr)

    stdscr.clear()

    x = int(curses.COLS / 2) - (int(len(CONTENT)) * 8)
    y = int(curses.LINES / 2) - 1

    for n in range(0, 16):
        draw_block(stdscr, x, y, n)
        stdscr.refresh()
        time.sleep(0.1)

    stdscr.getch()

curses.wrapper(main)
