#! /usr/bin/env python

from carrera import Carrera
from optparse import OptionParser

parser = OptionParser()

parser.add_option("-s", "--socket", dest="socket", default="/var/run/lirc/lircd",
                  help="Location of the lircd socket [default: %default]", metavar="PATH")
parser.add_option("-h", "--host", dest="host", default="localhost",
                  help="Host name to run TCP server on [default: %default]" , metavar="HOST")
parser.add_option("-p", "--port", dest="port", default=8099,
                  help="TCP port to listen on [default: %default]", metavar="PORT")
parser.add_option("-r", "--remote", dest="remote", default="carrera",
                  help="The name of the remote control in the lirc config [default: %default]",
                  metavar="NAME")
parser.add_option("-l", "--logfile", dest="logfile", default=None,
                  help="The path to a file to log output to [default: STDOUT]",
                  metavar="PATH")

c = Carrera()
c.run(players=[1, 2], port=9999, socket="/usr/local/var/run/lirc/lircd")
