#! /usr/bin/env python

import socket
import sys

"""A simple REPL to send commands to a Carrera server."""

host = sys.argv[1]
port = int(sys.argv[2])

def connect():
    global sock
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((host, port))

def send(command):
    sock.sendall(bytes(command, "utf-8"))
    resp = sock.recv(256)

    if len(resp) > 0:
        print("> %s" % resp)

    return resp

try:
    connect()
except:
    print("Cannot connect to %s:%d" % (host, port))
    sys.exit(1)

try:
    # Get input
    while True:
        command = input("# ")

        if command == "exit":
            break

        resp = send(command)

        if len(resp) == 0:
            connect()
            send(command)
except:
    print("Connection lost.")
finally:
    sock.close()

print("Exiting...")
