#! /usr/bin/env python

import socket
import sys

"""A simple REPL to send commands to a Carrera server."""

host = sys.argv[1]
port = int(sys.argv[2])

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

try:
    sock.connect((host, port))
except:
    print("Cannot connect to %s:%d" % (host, port))
    sys.exit(1)

try:
    # Get input
    while True:
        command = input("# ")

        if command == "exit":
            break

        sock.sendall(bytes(command, "utf-8"))
        print("> %s" % sock.recv(256))
        sock.connect((host, port))
except:
    print("Connection lost.")
finally:
    sock.close()

print("Exiting...")
